### ISSUE TITLE
Release new version to CocoaPods. (Last release was March 20 2015)

### ISSUE THREAD

**Issue by jawwad** [facebook/Tweaks#101]
The current version 2.0.0 was released on March 20 2015, and there have been many nice updates since then particularly support for configuring UIColor. It would be good to release a new version to CocoaPods.

I spent quite a bit of time trying to figure out why I couldn't get UIColor to show the "color adjustment view", and then realized that the reason it was working in the example project, but was not working in the version on CocoaPods was that v2.0.0 did not include that support.

**Comment by master-nevi** [comment]
+1

**Comment by grp** [comment]
Using #99 to track this.
