### ISSUE TITLE
Way of displaying a value?

### ISSUE THREAD

**Issue by jcampbell05** [facebook/Tweaks#105]
I want to show some debug information but not allow a user to tweak it.

**Comment by grp** [comment]
You can use the Tweaks API to get the tweak and read it's value, then show it however you want. I don't think this is something we'll likely build in directly, but it should be easy to build as a separate library!

**Comment by jcampbell05** [comment]
How would I go about making a custom FBTweak?

**Comment by grp** [comment]
You can get a `FBTweak` object with the shorthand `FBTweakInline()` macro, or find an existing tweak through the `FBTweakStore` object. See the "Advanced" section of the README: https://github.com/facebook/Tweaks#advanced
