### ISSUE TITLE
Present View Controller

### ISSUE THREAD

**Issue by jcampbell05** [facebook/Tweaks#106]
I would love to be able to present a VC from a Tweak.

**Comment by grp** [comment]
You should be able to do this with `FBTweakAction` and getting the `+keyWindow`: 

    FBTweakAction(@"Player", @"Audio", @"Volume", ^{
      UIViewController *viewController = [[MyViewController alloc] init];

      UIWindow *window = [UIApplication sharedApplication].keyWindow;
      [window.rootViewController presentViewController:viewController animated:YES completion:NULL];
    });

**Comment by jcampbell05** [comment]
Implemented this by recursively traversing the VC stack and presenting since the code above doesn't work but it would still be more convenient for Tweaks to support this.
