### ISSUE TITLE
NSInteger Support?

### ISSUE THREAD

**Issue by madclouds** [facebook/Tweaks#11]
When using an int - the tweak value is not converted correctly:

```
int gravityValue = FBTweakValue(@"Animation", @"Settings", @"Hide Gravity", 2);
```

Screenshot of output:
http://imgur.com/ZdTjNVD

**Comment by itsthejb** [comment]
I seem to still get this in 2.0.0:

![screen shot 2015-06-11 at 12 12 22](https://cloud.githubusercontent.com/assets/557391/8104717/232c1620-1033-11e5-8f37-d7a57fd7e021.png)

![screen shot 2015-06-11 at 12 12 06](https://cloud.githubusercontent.com/assets/557391/8104719/25d8f8a2-1033-11e5-918a-5d9510f922cd.png)
