### ISSUE TITLE
Need to Update the Release for the Pods.

### ISSUE THREAD

**Issue by jdjohns80** [facebook/Tweaks#111]
The current pod spec is still pushing version 2.0.0, and this is an outdated version which has an issue where you are not able to use this as a dll, and only are able to successfully use as a static library. This defeats the purpose of having a pod. The latest version fixed this issue, but a newer release was never created and pushed to the pod spec. This current issue makes the current pod version 2.0.0 unusable as a pod.

**Comment by jdjohns80** [comment]
duplicate issue this will be tracked under #99

**Comment by jdjohns80** [comment]
This issue needs to be addressed, the last issue was opened Dec 2015, and it is apparent that this is not being handled. Is their a reason the pods are not being bumped up to version 2.1.0?

**Comment by grp** [comment]
This is tracked by #99.
