### ISSUE TITLE
How to dimiss Tweaks before I present a new ViewController

### ISSUE THREAD

**Issue by billxie1988** [facebook/Tweaks#113]

**Comment by grp** [comment]
If you're using `FBTweakShakeWindow`, you can just dismiss the modal view controller on that window:

    [shakeWindow.rootViewController dismissViewControllerAnimated:YES completion:NULL];

If you're presenting a `FBTweakViewController` yourself, then you can dismiss it as any other view controller. In either case, the `completion:` parameter allows specifying a block to run after the view controller is dismissed.
