### ISSUE TITLE
Support list of items

### ISSUE THREAD

**Issue by kcharwood** [facebook/Tweaks#22]
It would be great to provide a list of items to select from, but I can't quite think of a good way to do it.

```
FBTweakValue(@"Fun", @"Times", @"List", 0, @[@"TEST1", @"TEST2", @"TEST3]);
```

Something along the lines of this where you specify the default index value, but the tweaks selection UI would drill down to a list selection showing the string values?

Maybe there is a fancy way to do this with NS_ENUM and NS_OPTIONS, but I havent figured out a good way to do it yet.

**Comment by grp** [comment]
Thanks @johntmcintosh!
