### ISSUE TITLE
Network Tweaks

### ISSUE THREAD

**Issue by Noeski** [facebook/Tweaks#43]
Right now it is a bit clumsy to have to open the Tweaks UI from inside of the app, make changes, and then close the UI to see them - so I created a Mac app that pairs with Tweaks in order to make changes from your desktop and have them take effect on the device over the network.

Is this something you would be interested in integrating?

Below are just some screenshots of a fully functional prototype that is paired with the test Tweaks project.

![tweaks](https://cloud.githubusercontent.com/assets/1153082/3516576/a54d3cd4-06e2-11e4-89d9-b6c2f478152f.png)
![tweaks-2](https://cloud.githubusercontent.com/assets/1153082/3516688/ecd79670-06e3-11e4-9c89-fd99c4b5a69c.png)

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
