### ISSUE TITLE
FBTweakBind lazily initialized objects

### ISSUE THREAD

**Issue by fatuhoku** [facebook/Tweaks#50]
In my app, I extend `NSParargraphStyle` with my own custom style that I make accessible through a lazily instantiated property.

```objc
static NSMutableParagraphStyle *style;

@implementation NSParagraphStyle (Styling)

+ (instancetype)abc_authoringParagraphStyle {
    if (style == nil) {
        style = [[NSParagraphStyle defaultParagraphStyle] mutableCopy];
        FBTweakBind(style, paragraphSpacing, ABCAuthoringModeTweakName, ABCAuthoringModeTextTweakName, @"Paragraph Spacing", 20.f, 0.f, 50.f);
    }
    return style;
}

@end
```

I try to use tweak bind such that value updates are set directly on the underlying object. However, I get a
`EXC_i386_IVOP` exception.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
