### ISSUE TITLE
FBTweakAction invoked on respective table cell scroll into view

### ISSUE THREAD

**Issue by ziprick** [facebook/Tweaks#83]
When I have more than a screen's worth of items within the FBTweakViewController for a category, and the first table cell item is for a FBTweakAction, if I scroll down so that the table cell item for that action scrolls out of view, and then scroll back up so that it comes back into view, it triggers the action inadvertently.

Is this a known issue?  I'd be glad to try and build a minimal test case for this when I have the time, but for right now all I can offer is that it happens with a table section with two action cells at the top, followed by several property sections with a variable number of items each (enough to allow the top section to be scrolled out of view)

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
