### ISSUE TITLE
`FBTweakBind` macro not working after telling Cocoapods to `use_frameworks!`

### ISSUE THREAD

**Issue by johnboiles** [facebook/Tweaks#86]
After switching my project over to using frameworks (by adding `use_frameworks!` in my Podfile and running `pod install`), `FBTweakBind` raises an assertion every time. Here is the offending code:

    FBTweakBind(self, host, @"API", @"Host Settings", @"Host", @"https://api.example.com");

This crashes at _FBTweakBindObserver.m:27 where the following assertion failing:

    NSAssert(tweak != nil, @"tweak is required");

This was working just fine before the switch to frameworks. If I remove `FBTweakBind` from my codebase, the app runs just fine. Any ideas?

**Comment by johnboiles** [comment]
Looks like I posted pre-maturely. Seems like it's a cocoapods issue with not setting the proper build options for Tweaks as a framework. I'll reopen if there are any TODOs on the Tweaks side.

**Comment by johnboiles** [comment]
Re-opening. Seems that removing `FBTweakBind` does allow the app to run, but no tweaks show up in the `FBTweakViewController`. I've confirmed that `-DFB_TWEAK_ENABLED=1` and `-DDEBUG=1` are being passed into clang for both files in my project, the Tweak files being compiled into the framework. Anything else I should check?

**Comment by grp** [comment]
When you use frameworks, the Tweaks are stored in many different libraries. Right now, Tweaks only looks at the app itself when searching for tweaks. #85 has a fix for this that's waiting on an update to merge; I'll talk to @darknoon about getting that updated.

**Comment by grp** [comment]
Landed a fix.

**Comment by johnboiles** [comment]
Woohoo!
