### ISSUE TITLE
Crash when Address Sanitizer is enabled in XCode 7.0 Beta

### ISSUE THREAD

**Issue by fsjack** [facebook/Tweaks#89]
app crash when goes to
[store tweakCategoryWithName:*entry->category];
saying that EXC_BAD_ACCESS.

Seem Address Sanitizer have done something with the memory layout which is not compatible with Tweaks.

**Comment by grp** [comment]
This looks like a bug in the address sanitizer — I'd suggest disabling Tweaks when building in that config.
