### ISSUE TITLE
UIAlertView is deprecated in iOS 9 warning in Xcode 7 GM

### ISSUE THREAD

**Issue by zodester** [facebook/Tweaks#92]
Currently when building tweaks into an iOS9 application there will be a depreciation warning regarding `UIAlertView`:

```
/Pods/Tweaks/FBTweak/_FBTweakCategoryViewController.m:108:5: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead
```

Looks like this method does a check for iOS 8 and uses UIAlertController where appropriate but the deprecation warning is not suppressed.

**Comment by grp** [comment]
Unfortunately, we can't fix this without also dropping iOS 7 compatibility. Once we drop that this will go away implicitly.

**Comment by kiritmodi2702** [comment]
Now You are use the UIAlertController instead of UIAlertView : See more reference of UIAlertController in Swift 👍  [https://iosdevcenters.blogspot.com/2016/03/uialertcontroller-in-swift.html](url)
