### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by johnboiles** [facebook/Tweaks#99]
Looks like the latest tag, 2.0.0, is ~10 months old. Might be worth bumping the version number so people can easily get the latest fixes (such as #85 which fixes framework support) via Cocoapods without having to reference the git repo like this:

```
pod 'Tweaks', :git => 'https://github.com/facebook/Tweaks.git',
```

**Comment by miketsprague** [comment]
+1

**Comment by goldierox** [comment]
Any possibility of tagging a new release and adding it to Cocoapods?

**Comment by jdjohns80** [comment]
The current pod spec is still pushing version 2.0.0, and this is an outdated version which has an issue where you are not able to use this as a dll, and only are able to successfully use as a static library. This defeats the purpose of having a pod. The latest version fixed this issue, but a newer release was never created and pushed to the pod spec.Can we possibly get an updated version released?

**Comment by brentleyjones** [comment]
Just ran into this myself.

**Comment by master-nevi** [comment]
2.0.0 is going to be 2 years old in 5 months. Even a stamped 2.1 tag would be nice, the pod doesn't have to be published if it's too much to ask.

@grp

**Comment by grp** [comment]
I pushed a 2.1.0 tag. I don't have CocoaPods on this machine to publish it, but hopefully one of the FB maintainers can take care of that. cc @nlutsenko @b3ll

**Comment by nlutsenko** [comment]
@grp, don't quite see the 2.1.0 tag :(
I can ship an update for Tweaks today, but need CocoaPods access - could you add me (nlutsenko(at)me.com). Thanks.

**Comment by warpling** [comment]
Took me too many hours to find this issue; would be great to mention more in the issue title!
 What's blocking release?

**Comment by b3ll** [comment]
Sorry about this, I'll get this fixed right now!

**Comment by b3ll** [comment]
Fixed! Sorry about the wait :(
